# Ім'я вашого workflow
name: CI Pipeline

# Коли запускати цей workflow
on:
  push:
    branches:
      - main # Запуск при кожному push у гілку main
  pull_request:
    branches:
      - main # Запуск при створенні pull request в main
  workflow_dispatch: # Можливість запуску вручну

# Налаштування завдань (jobs)
jobs:
  # Ідентифікатор завдання
  build-and-test:
    # Яка операційна система використовуватиметься
    runs-on: ubuntu-latest

    # Кроки виконання завдання
    steps:
      - name: Checkout code # Крок 1: завантаження коду репозиторію
        uses: actions/checkout@v4

      - name: Setup Node.js environment # Крок 2: налаштування Node.js середовища
        uses: actions/setup-node@v4
        with:
          node-version: "16.x"

      # - name: Install dependencies  # Крок 3: встановлення npm-залежностей
      #   run: npm ci

      - name: Run tests # Крок 4: запуск тестів
        run: npm run test

      # - name: Lint code # Крок 5: лінтинг коду
      #   run: npm run lint

      # - name: Deploy to GitHub Pages # Крок 6: деплой (наприклад, на GitHub Pages)
      #   if: github.ref == 'refs/heads/main' # Деплой тільки при пуші в main
      #   run: npm run deploy
